---
- name: Render DNS proxy JunOS template
  template:
    src: dns-proxy.set.j2
    dest: "rendered/{{ inventory_hostname }}-dns-proxy.set"

- name: Push DNS proxy server configuration to Junos devices
  juniper_junos_config:
    provider: "{{ netconf }}"
    load: 'set'
    src: "rendered/{{ inventory_hostname }}-dns-proxy.set"
