---

- hosts: timezone
  vars:
      debian_timezone: "{{ timezone }}"
  roles:
    - timezone-debian

- hosts: webservers
  roles:
    - ansible-apache2-debian

- hosts: router-fw
  roles:
    - ansible-junos-nameserver
    - ansible-junos-dns-proxy

...
