---
- name: Setup time zone and install ntp and rsyslog on Debian systems
  hosts: timezone
  vars:
      debian_timezone: "{{ timezone }}"
  roles:
    - { role: timezone-debian, tags: ["timezone", "debian"]

- name: Set up the web servers
  hosts: webservers
  roles:
    - { role: ansible-apache2-debian, tags: ["apache2", "webserver", "debian"] }
...
