---

- hosts: timezone
  vars:
      debian_timezone: "{{ timezone }}"
  roles:
    - timezone-debian

- hosts: client-int
  roles:
    - ansible-dns-debian

- hosts: webservers
  roles:
    - ansible-apache2-debian

- hosts: router-fw
  roles:
    - Juniper.junos
    - ansible-junos-nameserver
    - ansible-junos-dns-proxy
  connection: local

...
